const FALLBACK="../data/funds.json";let state={tab:"dashboard",q:"",data:null};
async function load(){try{const r=await fetch("../data/live.json",{cache:"no-store"});state.data=await r.json()}catch(e){const r=await fetch(FALLBACK);state.data=await r.json()}render()}
function setTab(t){state.tab=t;render()}
function funds(){return state.data.funds||[]}
function status(){return state.data.live?"LIVE DATA":"LIVE FEED NOT CONNECTED"}
function header(){return `<header class="top"><div class="brand">AIA ILP Performance</div><div class="sub">Singapore · Advisor Dashboard</div><div class="status"><span class="dot"></span>${status()}</div></header>`}
function dashboard(){let fs=funds();return `<section class="hero"><div class="label">Advisor view</div><h1>AIA ILP Performance</h1><p>Compare AIA fund performance against S&P 500 Total Return and each fund's official benchmark.</p></section><div class="grid"><div class="card"><div class="label">Funds tracked</div><div class="value">${fs.length}</div></div><div class="card"><div class="label">Benchmark</div><div class="value">S&P 500 TR</div></div><div class="card"><div class="label">Refresh</div><div class="value">Daily</div></div><div class="card"><div class="label">Policy return</div><div class="value">Separate</div></div></div><div class="section"><h2>Data integrity</h2><div class="notice">Only verified feed values will be shown as live. Fund-level return is kept separate from policy-level return.</div></div>`}
function fundView(){let a=funds().filter(f=>f.name.toLowerCase().includes(state.q.toLowerCase()));return `<input class="search" placeholder="Search AIA funds…" value="${state.q}" oninput="state.q=this.value;render()"><div class="section"><h2>${a.length} funds</h2><div class="fund-list">${a.map(f=>`<div class="fund"><div><div class="fund-name">${f.name}</div><div class="meta">${f.currency} · ${f.benchmark}</div></div><span class="badge">${f.status}</span></div>`).join("")}</div></div>`}
function compare(){return `<section class="hero"><div class="label">Comparison engine</div><h1>AIA Fund vs S&P 500 TR</h1><p>1Y, 3Y, 5Y, 10Y and risk metrics will calculate from aligned verified histories.</p></section><select class="select">${funds().map(f=>`<option>${f.name}</option>`).join("")}</select><div class="tabs"><button class="tab active">S&P 500 TR</button><button class="tab">Official Benchmark</button><button class="tab">Both</button></div><div class="grid">${["1Y","3Y CAGR","5Y CAGR","10Y CAGR","Max Drawdown","Volatility","Sharpe","$100k Value"].map(x=>`<div class="card"><div class="label">${x}</div><div class="value">—</div></div>`).join("")}</div>`}
function client(){return `<section class="hero"><div class="label">Client Presentation Mode</div><h1>Simple. Visual. Advisor-ready.</h1><p>Show fund performance, benchmark and growth of $100,000 without exposing internal technical details.</p></section><div class="notice">Client Mode will only display verified live values once the production feed is active.</div>`}
function render(){document.getElementById("app").innerHTML=`${header()}<main class="content">${state.tab==="dashboard"?dashboard():state.tab==="funds"?fundView():state.tab==="compare"?compare():client()}</main><nav class="bottom"><div class="nav">${[["dashboard","⌂","Dashboard"],["funds","◫","Funds"],["compare","⇄","Compare"],["client","◉","Client"]].map(x=>`<button class="${state.tab===x[0]?"active":""}" onclick="setTab('${x[0]}')"><span class="icon">${x[1]}</span>${x[2]}</button>`).join("")}</div></nav>`}
load();