const FALLBACK="./data/funds.json";
let state={tab:"dashboard",q:"",selected:null,data:null};
async function load(){try{const r=await fetch("./data/live.json",{cache:"no-store"});state.data=await r.json()}catch(e){const r=await fetch(FALLBACK);state.data=await r.json()}state.selected=state.data.funds&&state.data.funds[0]?state.data.funds[0].id:null;render()}
function setTab(t){state.tab=t;render()}
function funds(){return state.data&&state.data.funds?state.data.funds:[]}
function selected(){return funds().find(function(f){return f.id===state.selected})||funds()[0]}
function pct(v){return v==null?"—":Number(v).toFixed(2)+"%"}
function status(){return state.data&&state.data.live?"LIVE DATA":"LIVE FEED "+((state.data&&state.data.coverage&&state.data.coverage.aia_funds_live)||0)+"/"+((state.data&&state.data.coverage&&state.data.coverage.aia_funds_total)||funds().length)}
function header(){return '<header class="top"><div class="brand">AIA ILP Performance</div><div class="sub">Singapore · Advisor Dashboard</div><div class="status"><span class="dot"></span>'+status()+'</div></header>'}
function dashboard(){var fs=funds(),live=state.data&&state.data.coverage?state.data.coverage.aia_funds_live:0;return '<section class="hero"><div class="label">Advisor view</div><h1>AIA ILP Performance</h1><p>Verified AIA fund performance with S&P 500 Total Return reference data.</p></section><div class="grid"><div class="card"><div class="label">Funds tracked</div><div class="value">'+fs.length+'</div></div><div class="card"><div class="label">AIA live coverage</div><div class="value">'+live+'/'+fs.length+'</div></div><div class="card"><div class="label">Benchmark</div><div class="value">S&P 500 TR</div></div><div class="card"><div class="label">Refresh</div><div class="value">Daily</div></div></div><div class="section"><h2>Data integrity</h2><div class="notice">AIA values are read from AIA Singapore rendered fund pages. Benchmark data uses S&P 500 Total Return (^SP500TR). Policy-level returns remain separate.</div></div>'}
function fundView(){var a=funds().filter(function(f){return f.name.toLowerCase().includes(state.q.toLowerCase())});return '<input class="search" placeholder="Search AIA funds…" value="'+state.q+'" oninput="state.q=this.value;render()"><div class="section"><h2>'+a.length+' funds</h2><div class="fund-list">'+a.map(function(f){return '<button class="fund" onclick="state.selected=\\''+f.id+'\\';state.tab=\\'compare\\';render()"><div><div class="fund-name">'+f.name+'</div><div class="meta">'+f.currency+' · '+f.status+'</div></div><span class="badge">'+pct(f.oneYear)+'</span></button>'}).join("")+'</div></div>'}
function compare(){var f=selected();if(!f)return "";return '<section class="hero"><div class="label">Comparison engine</div><h1>'+f.name+'</h1><p>AIA fund performance vs S&P 500 Total Return. Official fund benchmark remains the primary like-for-like reference where applicable.</p></section><select class="select" onchange="state.selected=this.value;render()">'+funds().map(function(x){return '<option value="'+x.id+'" '+(x.id===f.id?"selected":"")+'>'+x.name+'</option>'}).join("")+'</select><div class="grid"><div class="card"><div class="label">1Y</div><div class="value">'+pct(f.oneYear)+'</div></div><div class="card"><div class="label">3Y CAGR</div><div class="value">'+pct(f.threeYear)+'</div></div><div class="card"><div class="label">5Y CAGR</div><div class="value">'+pct(f.fiveYear)+'</div></div><div class="card"><div class="label">10Y CAGR</div><div class="value">'+pct(f.tenYear)+'</div></div><div class="card"><div class="label">Since inception</div><div class="value">'+pct(f.sinceInception)+'</div></div><div class="card"><div class="label">Latest bid</div><div class="value">'+(f.latest==null?"—":Number(f.latest).toFixed(4))+'</div></div></div><div class="section"><h2>Source</h2><div class="notice">'+f.status+'. AIA performance is bid-to-bid with income/dividends reinvested, excluding certain policy-level fees and charges.</div></div>'}
function client(){var f=selected();return '<section class="hero"><div class="label">Client Presentation Mode</div><h1>'+((f&&f.name)||"AIA ILP Fund")+'</h1><p>Fund-level performance only. Policy charges, insurance costs and cash-flow timing are not included.</p></section><div class="grid"><div class="card"><div class="label">1 Year</div><div class="value">'+pct(f&&f.oneYear)+'</div></div><div class="card"><div class="label">5 Year CAGR</div><div class="value">'+pct(f&&f.fiveYear)+'</div></div><div class="card"><div class="label">10 Year CAGR</div><div class="value">'+pct(f&&f.tenYear)+'</div></div><div class="card"><div class="label">Latest bid</div><div class="value">'+(f&&f.latest!=null?Number(f.latest).toFixed(4):"—")+'</div></div></div><div class="notice">For client use: confirm the applicable policy, fees and charges before presenting policy-level outcomes.</div>'}
function render(){document.getElementById("app").innerHTML=header()+'<main class="content">'+(state.tab==="dashboard"?dashboard():state.tab==="funds"?fundView():state.tab==="compare"?compare():client())+'</main><nav class="bottom"><div class="nav">'+[["dashboard","⌂","Dashboard"],["funds","◫","Funds"],["compare","⇄","Compare"],["client","◉","Client"]].map(function(x){return '<button class="'+(state.tab===x[0]?"active":"")+'" onclick="setTab(\\''+x[0]+'\\')"><span class="icon">'+x[1]+'</span>'+x[2]+'</button>'}).join("")+'</div></nav>'}
load();